### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by tkernell** [tellor-io/telliot-core#161]
2021-12-03 15:36:35,882 - telliot_feed_examples.reporters.interval - ERROR - Estimated profitability below threshold.                                       
Traceback (most recent call last):                                                                                                                          
  File "/home/ubuntu/env/bin/telliot-examples", line 8, in <module>                                                                                         
    sys.exit(cli())                                                                                                                                         
  File "/home/ubuntu/env/lib/python3.8/site-packages/click/core.py", line 1128, in __call__                                                                 
    return self.main(*args, **kwargs)                                                                                                                       
  File "/home/ubuntu/env/lib/python3.8/site-packages/click/core.py", line 1053, in main                                                                     
    rv = self.invoke(ctx)                                                                                                                                   
  File "/home/ubuntu/env/lib/python3.8/site-packages/click/core.py", line 1659, in invoke                                                                   
    return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                                                 
  File "/home/ubuntu/env/lib/python3.8/site-packages/click/core.py", line 1395, in invoke                                                                   
    return ctx.invoke(self.callback, **ctx.params)                                                                                                          
  File "/home/ubuntu/env/lib/python3.8/site-packages/click/core.py", line 754, in invoke                                                                    
    return __callback(*args, **kwargs)                                                                                                                      
  File "/home/ubuntu/env/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func                                                             
    return f(get_current_context(), *args, **kwargs)                                                                                                        
  File "/home/ubuntu/env/lib/python3.8/site-packages/telliot_feed_examples/cli.py", line 190, in report                                                     
    _, _ = asyncio.run(legacy_reporter.report())                                                                                                            
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run                                                                                             
    return loop.run_until_complete(main)                                                                                                                    
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete                                                                         
    return future.result()                                                                                                                                  
  File "/home/ubuntu/env/lib/python3.8/site-packages/telliot_feed_examples/reporters/interval.py", line 328, in report                                      
    _, _ = await self.report_once()                                                                                                                         
  File "/home/ubuntu/env/lib/python3.8/site-packages/telliot_feed_examples/reporters/interval.py", line 261, in report_once                                 
    staked, status = await self.ensure_staked(gas_price_gwei)                                                                                               
  File "/home/ubuntu/env/lib/python3.8/site-packages/telliot_feed_examples/reporters/interval.py", line 62, in ensure_staked                                
    staker_info, read_status = await self.master.read(                                                                                                                           
  File "/home/ubuntu/env/lib/python3.8/site-packages/telliot_core/contract/contract.py", line 65, in read                                                   
    output = contract_function(**kwargs).call()                                                                                                               
  File "/home/ubuntu/env/lib/python3.8/site-packages/web3/contract.py", line 957, in call                                                                           
    return call_contract_function(                                                                                                                          
  File "/home/ubuntu/env/lib/python3.8/site-packages/web3/contract.py", line 1501, in call_contract_function                                                  
    return_data = web3.eth.call(                                                                                                                                    
  File "/home/ubuntu/env/lib/python3.8/site-packages/web3/module.py", line 57, in caller                                                                    
    result = w3.manager.request_blocking(method_str,                                                                                                          
  File "/home/ubuntu/env/lib/python3.8/site-packages/web3/manager.py", line 197, in request_blocking                                                        
    response = self._make_request(method, params)                                                                                                             
  File "/home/ubuntu/env/lib/python3.8/site-packages/web3/manager.py", line 150, in _make_request                                                           
    return request_func(method, params)                                                                                                                       
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__                                                                                                              
  File "/home/ubuntu/env/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters                                                
    response = make_request(method, params)                                                                                                                 
  File "/home/ubuntu/env/lib/python3.8/site-packages/web3/middleware/gas_price_strategy.py", line 90, in middleware                                           
    return make_request(method, params)                                                                                                                     
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__                                                                                 
  File "/home/ubuntu/env/lib/python3.8/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters                                                                        
    response = make_request(method, formatted_params)                                                                                                            
  File "/home/ubuntu/env/lib/python3.8/site-packages/web3/middleware/attrdict.py", line 33, in middleware                                                                        
    response = make_request(method, params)                                                                                                                 
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__                                                                                 
  File "/home/ubuntu/env/lib/python3.8/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters                                                                          
    response = make_request(method, formatted_params)                                                                                                            
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__                                                                                                
  File "/home/ubuntu/env/lib/python3.8/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters                                           
    response = make_request(method, formatted_params)                                                                                                       
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__                                                                               
  File "/home/ubuntu/env/lib/python3.8/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters                                           
    response = make_request(method, formatted_params)                                                                                                       
  File "/home/ubuntu/env/lib/python3.8/site-packages/web3/middleware/buffered_gas_estimate.py", line 40, in middleware                                      
    return make_request(method, params)                                                                                                                     
  File "/home/ubuntu/env/lib/python3.8/site-packages/web3/providers/websocket.py", line 144, in make_request                                                  
    return future.result()                                                                                                                                       
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result                                                                                     
    return self.__get_result()                                                                                                                                      
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result                                                                                  
    raise self._exception                                                                                                                                                    
  File "/home/ubuntu/env/lib/python3.8/site-packages/web3/providers/websocket.py", line 130, in coro_make_request                                                            
    await asyncio.wait_for(                                                                                                                                                  
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for                                                                                                          
    raise exceptions.TimeoutError()                                                                                                                                          
asyncio.exceptions.TimeoutError

**Comment by oraclown** [comment]
I think we can close this because we've accounted for errors reading from master contract. @clamdad @tallywiesenberg thoughts?
