### ISSUE TITLE
ModuleNotFoundError: No module named 'telliot_core.utils.log' 

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/telliot-core#293]
Running the latest in the main `telliot-feeds` repo & the latest in the `telliot-core` repo gives in this error: 

```Traceback (most recent call last):
  File "/home/ubuntu/tenv_dev/bin/telliot-examples", line 5, in <module>
    from telliot_feed_examples.cli import cli
  File "/home/ubuntu/tenv_dev/lib/python3.9/site-packages/telliot_feed_examples/cli.py", line 25, in <module>
    from telliot_feed_examples.reporters.rng_interval import RNGReporter
  File "/home/ubuntu/tenv_dev/lib/python3.9/site-packages/telliot_feed_examples/reporters/rng_interval.py", line 15, in <module>
    from telliot_core.utils.log import get_logger
ModuleNotFoundError: No module named 'telliot_core.utils.log'```

**Comment by oraclown** [comment]
I think I fixed this in an unrelated PR, reopen if you encounter it again
