### ISSUE TITLE
Error when using latest docker image

### ISSUE THREAD

**Issue by oraclown** [tellor-io/telliot-core#344]
Using `telliot config init`:
```
# telliot config init
server rejected WebSocket connection: HTTP 401
Could not connect to RPC endpoint at: wss://mainnet.infura.io/ws/v3/{INFURA_API_KEY}
Traceback (most recent call last):
  File "/usr/local/bin/telliot", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1654, in invoke
    super().invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/telliot_feeds/cli/main.py", line 63, in main
    ctx.obj["CHAIN_ID"] = accounts[0].chains[0]
IndexError: list index out of range
```
Trying to add an account:
```
# telliot account add dev1 *****.. 10200
server rejected WebSocket connection: HTTP 401
Could not connect to RPC endpoint at: wss://mainnet.infura.io/ws/v3/{INFURA_API_KEY}
Traceback (most recent call last):
  File "/usr/local/bin/telliot", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1654, in invoke
    super().invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/telliot_feeds/cli/main.py", line 63, in main
    ctx.obj["CHAIN_ID"] = accounts[0].chains[0]
IndexError: list index out of range
```

**Comment by oraclown** [comment]
But you don't get the error when you use chained to add account:
```
# chained add dev1 ****... 10200
Enter encryption password for dev1: 
Confirm password: 
Added new account dev1 (address= 0x8d8d2006a485fa4a75dfd8da8f63da31401b8fa2) for use on chains (10200,)
```

**Comment by oraclown** [comment]
Adding an account allows you to report. Also, all the relevant files were created w/ `telliot config init`, so the error was thrown after

**Comment by oraclown** [comment]
A short-term solution is to update the docs to make sure new users add an account before doing anything else..

**Comment by oraclown** [comment]
Need to update the release process to include some specific sanity checks for tests on local machine:
- change name of `.chained_accounts` file in `~` (root dir)
- change name of `telliot` folder in `~`
- try `telliot config init`
- try reporting
- try the main newly-added features
